-- This migration is superseded by 004_fix_bookings_and_profiles_clean.sql
-- All booking functions have been updated there with correct column names.
-- Keeping this as a no-op for migration continuity.
